require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SetbreaksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Setbreak. As you add validations to Setbreak, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SetbreaksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all setbreaks as @setbreaks" do
      setbreak = Setbreak.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:setbreaks)).to eq([setbreak])
    end
  end

  describe "GET #show" do
    it "assigns the requested setbreak as @setbreak" do
      setbreak = Setbreak.create! valid_attributes
      get :show, {:id => setbreak.to_param}, valid_session
      expect(assigns(:setbreak)).to eq(setbreak)
    end
  end

  describe "GET #new" do
    it "assigns a new setbreak as @setbreak" do
      get :new, {}, valid_session
      expect(assigns(:setbreak)).to be_a_new(Setbreak)
    end
  end

  describe "GET #edit" do
    it "assigns the requested setbreak as @setbreak" do
      setbreak = Setbreak.create! valid_attributes
      get :edit, {:id => setbreak.to_param}, valid_session
      expect(assigns(:setbreak)).to eq(setbreak)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Setbreak" do
        expect {
          post :create, {:setbreak => valid_attributes}, valid_session
        }.to change(Setbreak, :count).by(1)
      end

      it "assigns a newly created setbreak as @setbreak" do
        post :create, {:setbreak => valid_attributes}, valid_session
        expect(assigns(:setbreak)).to be_a(Setbreak)
        expect(assigns(:setbreak)).to be_persisted
      end

      it "redirects to the created setbreak" do
        post :create, {:setbreak => valid_attributes}, valid_session
        expect(response).to redirect_to(Setbreak.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved setbreak as @setbreak" do
        post :create, {:setbreak => invalid_attributes}, valid_session
        expect(assigns(:setbreak)).to be_a_new(Setbreak)
      end

      it "re-renders the 'new' template" do
        post :create, {:setbreak => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested setbreak" do
        setbreak = Setbreak.create! valid_attributes
        put :update, {:id => setbreak.to_param, :setbreak => new_attributes}, valid_session
        setbreak.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested setbreak as @setbreak" do
        setbreak = Setbreak.create! valid_attributes
        put :update, {:id => setbreak.to_param, :setbreak => valid_attributes}, valid_session
        expect(assigns(:setbreak)).to eq(setbreak)
      end

      it "redirects to the setbreak" do
        setbreak = Setbreak.create! valid_attributes
        put :update, {:id => setbreak.to_param, :setbreak => valid_attributes}, valid_session
        expect(response).to redirect_to(setbreak)
      end
    end

    context "with invalid params" do
      it "assigns the setbreak as @setbreak" do
        setbreak = Setbreak.create! valid_attributes
        put :update, {:id => setbreak.to_param, :setbreak => invalid_attributes}, valid_session
        expect(assigns(:setbreak)).to eq(setbreak)
      end

      it "re-renders the 'edit' template" do
        setbreak = Setbreak.create! valid_attributes
        put :update, {:id => setbreak.to_param, :setbreak => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested setbreak" do
      setbreak = Setbreak.create! valid_attributes
      expect {
        delete :destroy, {:id => setbreak.to_param}, valid_session
      }.to change(Setbreak, :count).by(-1)
    end

    it "redirects to the setbreaks list" do
      setbreak = Setbreak.create! valid_attributes
      delete :destroy, {:id => setbreak.to_param}, valid_session
      expect(response).to redirect_to(setbreaks_url)
    end
  end

end
